language: generic
sudo: required
services:
  - docker

before-install:
  - docker build -t image-name -f Dockerfile.dev .

script:
  - docker run -e CI=true image-name npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-482259169052"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
